export const texts = {
  Index: "Indeks",
  Editor: "Edytor",
  ConfigFiles: "Pliki konfiguracyjne",
  ConnectionString: "Connection String",
  ApplicationUrl: "URL Aplikacji",
  ApplicationName: "Nazwa Aplikacji (ścieżka w IIS)",
  ModulesPortStartIndex: "Najniższy Port",
  ModulesPortEndIndex: "Najwyzszy Port",
  DiagnosticMode: "Tryb Diagnostyczny",
  WorkingDirectory: "Katalog roboczy",
  GoBack: "Powrót",
  IpFilteringOption: "Filtrowanie IP",
  AllowedAddresses: "Dozwolone Adresy",
  BlockedAddresses: "Blokowane Adresy",
  Events: "Zdarzenia",
  ErrorOccurred: "Wystąpił błąd",
  FileMissing: "Plik zagubiony",
  NewFileAdded: "Znaleziono nowy plik",
  PleaseEnterWorkingDirectory: "Ścieżka do katalogu roboczego jest pusta",
  RetrieveFile: "Przywróć Plik",
  TrackFile: "Śledź Plik",
  NoEvents: "Nie ma żadnych zdarzeń 👌",
  SetOfIpAddresses: "Zbiór adresów IP",
  ProxyWindowsEnable: "Obsługa proxy",
  ProxyIPs: "Zbiór adresow IP proxy",
  Save: "Zapisz",
  OutsideModules: "Zewnętrzne moduły",
  ShowOfflinePageWhenERDBIsOffline:
    "Wyświetlanie strony offline (jeśli baza danych jest offline)",
  ShowOfflinePageNow: "Wyświetlanie strony offline",
  XFrameOptions: "Ustawienie x-frame",
  AllowShowPortalInIframe: "Wyświetl portal w iframe",
  AllowShowPortalInIFrameOnlyFromURL: "Wyświetl portal w iframe z URL-a",
  SolveConflict: "Rozwiąż konflikt",
  FileContentConflict: "Zawartość pliku została zmieniona",
  OldContent: "Stara zawartość",
  NewContent: "Nowa zawartość",
  Loading: "Wczytywanie...",
  Ignore: "Zignoruj",
  Forget: "Zapomnij",
};
