name: Build, Test and Release

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install
        run: yarn install --no-progress --non-interactive --skip-integrity-check --production
      - name: Test and Lint
        run: yarn ci
      - name: Build
        run: yarn build
        env:
          CI: true
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install --no-progress --non-interactive --skip-integrity-check --production --frozen-lockfile
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
